# Generated by Django 2.0.1 on 2018-03-07 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Info',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=100, unique=True)),
                ('host_ip', models.GenericIPAddressField()),
                ('host_type', models.CharField(max_length=100)),
                ('host_location', models.CharField(max_length=100)),
                ('host_os', models.CharField(max_length=100)),
                ('host_monitor', models.BooleanField()),
                ('host_ctime', models.DateTimeField(auto_now_add=True)),
                ('host_uptime', models.DateTimeField(auto_now=True)),
                ('host_info', models.TextField()),
                ('host_user', models.ForeignKey(on_delete=bool, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hostinfo',
            },
        ),
    ]
