# Generated by Django 2.0.1 on 2018-03-07 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_info',
            name='host_status',
            field=models.CharField(choices=[(0, '生产环境'), (1, '测试环境')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
