# Generated by Django 2.0.1 on 2018-03-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_host_info_host_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='host_status',
            field=models.IntegerField(choices=[(0, '生产环境'), (1, '测试环境')], max_length=100),
        ),
    ]
