# Generated by Django 2.0.1 on 2018-03-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180307_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_info',
            name='host_status',
            field=models.CharField(choices=[('生产环境', '生产环境'), ('测试环境', '测试环境')], max_length=100),
        ),
    ]
